= SonarQube Scanner
Fábio Luciano <fabio@naoimporta.com>
:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

== Compatibilidade

SonarQube Scanner 3.2.0.1227

Notas::
 * O SGBD referenciado na string de conexão será utilizado para carregar o conector a ser utilizado

== Origem do código fonte

[width="100%", options="header",frame="topbot"] 
|=======
| Variável | Descrição | Exemplo
| SOURCE_METHOD | Origem do código fonte | *GIT* ou *VOLUME*
|=======

=== Git

O clone do repositório, na imagem será feito em `/opt/source`

[width="100%", options="header",frame="topbot"] 
|=======
| Variável | Descrição | Valor Padrão
| GIT_EMAIL | E-mail do usuário responsável pelo commit ( será o email do usuário configurado no gitconfig ) | N/A
| GIT_URL | URL do repositório | https://github.com/integr8/liquibase-helper/
| GIT_USER | Usuário utilizado para autencicação no repositório | N/A
| GIT_PASS | Senha utilização para autenticação no repositório | N/A
|=======

=== Volume

Caso os procedimentos serão executados em um código já clonado, o `root` do repositório deverá ser referenciado como um volume em `/opt/source`

[caption="Exemplo: "]
.Utilização da imagem com volume
===============================================================
[source, shell]
--------------------------------------------------------------
docker run --rm \
  -e 'SOURCE_METHOD=VOLUME' \
  -e 'LIQUIBASE_DB_URL=jdbc:postgresql://172.17.0.3:5432/db' \
  -e 'LIQUIBASE_DB_SCHEME=public' \
  -e 'LIQUIBASE_DB_USER=user' \
  -e 'LIQUIBASE_DB_PASS=password' \
  -v $(pwd)/source:/opt/source  \ # <1>
liquibase-helper status
--------------------------------------------------------------
<1> Referencia ao volume, sendo que a localização atual no host é na raiz do repositório do projeto.
===============================================================
